### PR TITLE
fix: latex rendering (issue Latex Rendering Problem #68)

### PR DESCRIPTION
**Pull request by enfycius**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/docu-notion/73)

### CODE REVIEW

**Comment by hatton** [comment]
Thanks for this. There are a few problems that you will see if you turn on the eslint extension in vscode:

image

After you have fixed those, you can amend and then force push your same commit to your repo.

**Comment by enfycius** [comment]
@hatton Ok. I have just improved the existing one. Please check it.

**Comment by hatton** [comment]
Great, thanks for that. Unfortunately, we've found other problems that come in with the new `notion-to-md`, so we can't upgrade yet. Once we work those out, we'll be able to merge this.

**Comment by enfycius** [comment]
Oh ! I'm okay. Very thanks. As I previously mentioned, it is an honor to me.

**Comment by andrew-polk** [comment]
We actually ended up upgrading to the latest notion-to-md for #70.
You can try it out in version 0.14.0-alpha.3.

**Comment by enfycius** [comment]
Ok. Thanks :)

**Pull request closed without merging**
