### PR TITLE
fix: Use video player only for embedded videos (#60)

### PR DESCRIPTION
**Pull request by andrew-polk**
https://github.com/sillsdev/docu-notion/issues/60

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/docu-notion/67)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/docu-notion/67)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/transform.ts` line 147 at r1](https://reviewable.io/reviews/sillsdev/docu-notion/67#-NbPelH2DYlk2uYFOtDY:-NbPelH2DYlk2uYFOtDZ:bir7u73) ([raw file](https://github.com/sillsdev/docu-notion/blob/f6b1b7b353d1ce229280de705dd8031cd32692f8/src/transform.ts#L147)):*
> ```XML
>           // add any library imports
>           if (!context.imports) context.imports = [];
>           mod.imports?.forEach(imp => context.imports!.push(imp));
> ```

To avoid the `Forbidden non-null assertion`, you could do

` context.imports?.push(...mod.imports || []);`
___
*[`src/plugins/VideoTransformer.ts` line 9 at r1](https://reviewable.io/reviews/sillsdev/docu-notion/67#-NbPcOc64NM7SN-ekwfC:-NbPcOc64NM7SN-ekwfD:b9tmwas) ([raw file](https://github.com/sillsdev/docu-notion/blob/f6b1b7b353d1ce229280de705dd8031cd32692f8/src/plugins/VideoTransformer.ts#L9)):*
> ```XML
>       type: "video",
>       getStringFromBlock: async (context, block) => {
>         const blockAsAny = block as any;
> ```

You can avoid `any` here, something like this:

```TS
        const video = (block as VideoBlockObjectResponse).video;

        if (video.type === "external") {

          context.imports = [`import ReactPlayer from "react-player";`];

          return `<ReactPlayer controls url="${video.external.url}" />`;
 else {

          error(`Docunotion cannot handle this video type: ${video.type}`);
           ...
```
___
*[`src/plugins/VideoTransformer.ts` line 11 at r1](https://reviewable.io/reviews/sillsdev/docu-notion/67#-NbPd9hK5NhNI33A_sY0:-NbPd9hK5NhNI33A_sY1:b-z778gq) ([raw file](https://github.com/sillsdev/docu-notion/blob/f6b1b7b353d1ce229280de705dd8031cd32692f8/src/plugins/VideoTransformer.ts#L11)):*
> ```XML
>         const blockAsAny = block as any;
>         if (blockAsAny?.video?.external?.url) {
>           context.imports = [`import ReactPlayer from "react-player";`];
> ```

Should this be something like 
```TS
context.imports += `import ReactPlayer from "react-player";`
```

So that it doesn't collide with imports from other plugins?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/docu-notion/67)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[`src/transform.ts` line 147 at r1](https://reviewable.io/reviews/sillsdev/docu-notion/67#-NbPelH2DYlk2uYFOtDY:-NbQSYZCDOPsc4mZFFlW:boyexbg) ([raw file](https://github.com/sillsdev/docu-notion/blob/f6b1b7b353d1ce229280de705dd8031cd32692f8/src/transform.ts#L147)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

To avoid the `Forbidden non-null assertion`, you could do

` context.imports?.push(...mod.imports || []);`
</blockquote></details>

Done. Thanks.
___
*[`src/plugins/VideoTransformer.ts` line 9 at r1](https://reviewable.io/reviews/sillsdev/docu-notion/67#-NbPcOc64NM7SN-ekwfC:-NbR18Sg50hIH7ul4dhJ:boyexbg) ([raw file](https://github.com/sillsdev/docu-notion/blob/f6b1b7b353d1ce229280de705dd8031cd32692f8/src/plugins/VideoTransformer.ts#L9)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

You can avoid `any` here, something like this:

```TS
        const video = (block as VideoBlockObjectResponse).video;

        if (video.type === "external") {

          context.imports = [`import ReactPlayer from "react-player";`];

          return `<ReactPlayer controls url="${video.external.url}" />`;
 else {

          error(`Docunotion cannot handle this video type: ${video.type}`);
           ...
```
</blockquote></details>

Done. Thanks.
___
*[`src/plugins/VideoTransformer.ts` line 11 at r1](https://reviewable.io/reviews/sillsdev/docu-notion/67#-NbPd9hK5NhNI33A_sY0:-NbR1CCi75iCC46XSNrF:b-qyismq) ([raw file](https://github.com/sillsdev/docu-notion/blob/f6b1b7b353d1ce229280de705dd8031cd32692f8/src/plugins/VideoTransformer.ts#L11)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Should this be something like 
```TS
context.imports += `import ReactPlayer from "react-player";`
```

So that it doesn't collide with imports from other plugins? 
</blockquote></details>

Yep!
Good catch.

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/docu-notion/67)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`src/plugins/pluginTypes.ts` line 78 at r2](https://reviewable.io/reviews/sillsdev/docu-notion/67#-Nba2OlvAYaUw9SiLmbg:-Nba2OlvAYaUw9SiLmbh:b-bry649) ([raw file](https://github.com/sillsdev/docu-notion/blob/7390e987956c71b2e11cbb730d0f30013147112d/src/plugins/pluginTypes.ts#L78)):*
> ```XML
>   counts: ICounts;
> 
>   // If the output is creating things like react elements, you can import their definitions here
> ```

Let's set the comment to emphasize that you should append to this

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/docu-notion/67)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[`src/plugins/pluginTypes.ts` line 78 at r2](https://reviewable.io/reviews/sillsdev/docu-notion/67#-Nba2OlvAYaUw9SiLmbg:-NbaIrFpAIxSCO-wnZsz:b-896fix) ([raw file](https://github.com/sillsdev/docu-notion/blob/7390e987956c71b2e11cbb730d0f30013147112d/src/plugins/pluginTypes.ts#L78)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Let's set the comment to emphasize that you should append to this
</blockquote></details>

Done.

**Review by hatton — COMMENTED** [review]
> Reviewed 5 of 8 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/docu-notion/67)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

**Pull request merged**
