### PR TITLE
Resolving a Latex Rendering Problem

### PR DESCRIPTION
**Pull request by enfycius**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/docu-notion/71)

### CODE REVIEW

**Comment by enfycius** [comment]
It is my mistake to upload the my Notion API key. However, I am fine because I already removed the key and reissued a new key.

**Comment by hatton** [comment]
@enfycius Great start. Here are some next steps for you:

* Make sure that the only things in the diff are what is needed for this change. There should not be anything else (for example, do not add additional parameters to the `ts` command).
* The `package-lock.json` you submitted removed the `resolved` and `integrity` fields. I don't know what causes this, but see [this](https://github.com/npm/cli/issues/4263).
* Do not change the visibility of private members by adding `export`, even if this helps you write the unit test. Doing that is a big enough deal that we'd have to have a conversation first to make sure it is really needed. If you need help writing the test without these, just let us know, we can help.
* Create a named branch. "issue-68/latex-rendering" would be great
* Squash your commits down to one, with a commit message like "fix: latex rendering (issue #68)".

Thanks!

**Comment by enfycius** [comment]
@hatton Ok thanks. First, I will have to tackle these things you suggest to me. But, I can't spend more time because of a lab research. So, I really need your help about writing test code.

**Comment by enfycius** [comment]
Of course, If you can provide some time to me, I will have to try a various things. I think that it is possible to test this code without modifying a existing code. For example, I can indirectly test this code through the existing function with the public modifiers.

**Pull request closed without merging**
