### PR TITLE
fix: #21 Escape html (e.g. < becomes &lt;)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/docu-notion/26)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
This feels dumb to say, but it's not obvious to me what the logic of escaping `code` should be? Like my first thought is that `code` blocks *do* need to be escaped. Can you add a comment explaining what the behavior is that we need? Thx.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/docu-notion/26#-:-NIYGTMoDT4_pWH5rec9:b-jbdr53)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by andrew-polk** [comment]
Sorry; I merged this, thinking to not bother you with a review.
Yes, I'll add comments.

**Comment by andrew-polk** [comment]
Done.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/docu-notion/26)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[`src/pull.ts` line 291 at r1](https://reviewable.io/reviews/sillsdev/docu-notion/26#-NIrKXid2_C6gNrj6JTA:-NIrKXid2_C6gNrj6JTB:by46mt2) ([raw file](https://github.com/sillsdev/docu-notion/blob/9e78a006edba7df7215f481e2428b4d6db04913e/src/pull.ts#L291)):*
> ```XML
>       ) {
>         rt.plain_text = rt.plain_text
>           .replaceAll("<", "&lt;")
> ```

Are you sure this is enough? I would have expected to see at least a replacement for ampersand (first!). I presume this text is not going to become part of an attribute value so we don't need to worry about anything that is special there...

**Comment by andrew-polk** [comment]
*[`src/pull.ts` line 291 at r1](https://reviewable.io/reviews/sillsdev/docu-notion/26#-NIrKXid2_C6gNrj6JTA:-NIsghIb1H1uDRvqJXN4:b-cg44ce) ([raw file](https://github.com/sillsdev/docu-notion/blob/9e78a006edba7df7215f481e2428b4d6db04913e/src/pull.ts#L291)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Are you sure this is enough? I would have expected to see at least a replacement for ampersand (first!). I presume this text is not going to become part of an attribute value so we don't need to worry about anything that is special there...
</blockquote></details>

I should have explained more in the comments.
Yes, it is enough because it (whatever is going from markdown to html... docusaurus, right) is only finding things which look like tags and trying to interpret them, not trying to turn every string into html.

**Pull request merged**
